
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/usr/local/NVIDIA-Nsight-Compute/"
      - "/opt/cuda/bin/"
      - "/root/.bun/bin/"
      - "/root/.vscode-server/bin/7d842fb85a0275a4a8e4d7e040d2625abbf7f084/bin/remote-cli/"
      - "/root/.cargo/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/usr/lib/wsl/lib/"
      - "/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v13.0/bin/x64/"
      - "/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v13.0/bin/"
      - "/mnt/c/Program Files (x86)/Common Files/Oracle/Java/java8path/"
      - "/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath/"
      - "/mnt/c/Program Files/Oculus/Support/oculus-runtime/"
      - "/mnt/c/WINDOWS/system32/"
      - "/mnt/c/WINDOWS/"
      - "/mnt/c/WINDOWS/System32/Wbem/"
      - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
      - "/mnt/c/WINDOWS/System32/OpenSSH/"
      - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "/mnt/d/Node.js/"
      - "/mnt/d/Git/cmd/"
      - "/mnt/c/Program Files/dotnet/"
      - "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/"
      - "/mnt/c/ProgramData/chocolatey/bin/"
      - "/mnt/c/Users/there/miniconda3/"
      - "/mnt/c/Users/there/miniconda3/Scripts/"
      - "/mnt/c/Users/there/miniconda3/condabin/"
      - "/mnt/c/Program Files/NVIDIA Corporation/Nsight Compute 2025.3.1/"
      - "/mnt/c/Program Files/Docker/Docker/resources/bin/"
      - "/mnt/c/Users/there/.cargo/bin/"
      - "/mnt/c/Users/there/AppData/Local/Programs/Python/Python311/Scripts/"
      - "/mnt/c/Users/there/AppData/Local/Programs/Python/Python311/"
      - "/mnt/c/W/"
      - "/opt/cuda/nsight_compute/"
      - "/opt/cuda/nsight_systems/bin/"
      - "/usr/bin/site_perl/"
      - "/usr/bin/vendor_perl/"
      - "/usr/bin/core_perl/"
      - "/root/.local/bin/"
      - "/root/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/"
    searched_directories:
      - "/usr/local/NVIDIA-Nsight-Compute/uname"
      - "/opt/cuda/bin/uname"
      - "/root/.bun/bin/uname"
      - "/root/.vscode-server/bin/7d842fb85a0275a4a8e4d7e040d2625abbf7f084/bin/remote-cli/uname"
      - "/root/.cargo/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
    found: "/usr/sbin/uname"
    search_context:
      ENV{PATH}:
        - "/usr/local/NVIDIA-Nsight-Compute"
        - "/opt/cuda/bin"
        - "/root/.bun/bin"
        - "/root/.vscode-server/bin/7d842fb85a0275a4a8e4d7e040d2625abbf7f084/bin/remote-cli"
        - "/root/.cargo/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/usr/lib/wsl/lib"
        - "/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v13.0/bin/x64"
        - "/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v13.0/bin"
        - "/mnt/c/Program Files (x86)/Common Files/Oracle/Java/java8path"
        - "/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath"
        - "/mnt/c/Program Files/Oculus/Support/oculus-runtime"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/WINDOWS/System32/OpenSSH/"
        - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common"
        - "/mnt/d/Node.js/"
        - "/mnt/d/Git/cmd"
        - "/mnt/c/Program Files/dotnet/"
        - "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR"
        - "/mnt/c/ProgramData/chocolatey/bin"
        - "/mnt/c/Users/there/miniconda3"
        - "/mnt/c/Users/there/miniconda3/Scripts"
        - "/mnt/c/Users/there/miniconda3/condabin"
        - "/mnt/c/Program Files/NVIDIA Corporation/Nsight Compute 2025.3.1/"
        - "/mnt/c/Program Files/Docker/Docker/resources/bin"
        - "/mnt/c/Program Files (x86)/Common Files/Oracle/Java/java8path"
        - "/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath"
        - "/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v13.0/bin/x64"
        - "/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v13.0/bin"
        - "/mnt/c/Program Files/Oculus/Support/oculus-runtime"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/WINDOWS/System32/OpenSSH/"
        - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common"
        - "/mnt/d/Node.js/"
        - "/mnt/d/Git/cmd"
        - "/mnt/c/Program Files/dotnet/"
        - "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR"
        - "/mnt/c/ProgramData/chocolatey/bin"
        - "/mnt/c/Users/there/miniconda3"
        - "/mnt/c/Users/there/miniconda3/Scripts"
        - "/mnt/c/Users/there/miniconda3/condabin"
        - "/mnt/c/Program Files/NVIDIA Corporation/Nsight Compute 2025.3.1/"
        - "/mnt/c/Program Files/Docker/Docker/resources/bin"
        - "/mnt/c/Users/there/.cargo/bin"
        - "/mnt/c/Users/there/AppData/Local/Programs/Python/Python311/Scripts/"
        - "/mnt/c/Users/there/AppData/Local/Programs/Python/Python311/"
        - "/mnt/c/Program Files/Oculus/Support/oculus-runtime"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/W"
        - "/opt/cuda/bin"
        - "/opt/cuda/nsight_compute"
        - "/opt/cuda/nsight_systems/bin"
        - "/usr/bin/site_perl"
        - "/usr/bin/vendor_perl"
        - "/usr/bin/core_perl"
        - "/root/.local/bin"
        - "/root/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand"
        - "/root/.local/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.6.87.2-microsoft-standard-WSL2 - x86_64
...
