receivers:
  - name: default
  - name: qallow-auto-halt
    webhook_configs:
      - url: http://qallow-ops/auto-halt
route:
  receiver: default
  routes:
    - match:
        severity: critical
      receiver: qallow-auto-halt
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    receivers:
      - name: default
      - name: qallow-auto-halt
        webhook_configs:
          - url: http://qallow-ops/auto-halt
    route:
      receiver: default
      routes:
        - match:
            severity: critical
          receiver: qallow-auto-halt
