apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: qallow
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: qallow
        static_configs:
          - targets:
            - qallow-service:8080
