---
# Phase 13 Harmonic Service Deployment

apiVersion: v1
kind: ConfigMap
metadata:
  name: phase13-config
  namespace: qallow
data:
  config.json: |
    {
      "service_name": "phase13-harmonic",
      "grpc_port": 50052,
      "metrics_port": 8081,
      "log_level": "info",
      "enable_cuda": true,
      "cuda_device": 0,
      "checkpoint_interval": 500,
      "telemetry_batch_size": 50,
      "ethics_threshold": 2.9,
      "convergence_threshold": 0.001
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qallow-phase13
  namespace: qallow
  labels:
    app: qallow-phase13
    phase: "13"
    component: harmonic
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: qallow-phase13
  template:
    metadata:
      labels:
        app: qallow-phase13
        phase: "13"
        component: harmonic
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: qallow-sa
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - qallow-phase13
              topologyKey: kubernetes.io/hostname
      containers:
      - name: phase13
        image: qallow/phase13:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: grpc
          containerPort: 50052
          protocol: TCP
        - name: metrics
          containerPort: 8081
          protocol: TCP
        env:
        - name: QALLOW_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: QALLOW_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: QALLOW_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ENABLE_CUDA
          value: "true"
        - name: CUDA_DEVICE
          value: "0"
        - name: ETHICS_THRESHOLD
          value: "2.9"
        volumeMounts:
        - name: config
          mountPath: /etc/qallow
          readOnly: true
        - name: data
          mountPath: /var/qallow/data
        - name: logs
          mountPath: /var/qallow/logs
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: 1
        livenessProbe:
          grpc:
            port: 50052
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          grpc:
            port: 50052
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config
        configMap:
          name: phase13-config
      - name: data
        emptyDir:
          sizeLimit: 10Gi
      - name: logs
        emptyDir:
          sizeLimit: 5Gi
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: qallow-phase13
  namespace: qallow
  labels:
    app: qallow-phase13
    phase: "13"
spec:
  type: ClusterIP
  selector:
    app: qallow-phase13
  ports:
  - name: grpc
    port: 50052
    targetPort: 50052
    protocol: TCP
  - name: metrics
    port: 8081
    targetPort: 8081
    protocol: TCP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qallow-phase13-hpa
  namespace: qallow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qallow-phase13
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: qallow-phase13-pdb
  namespace: qallow
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: qallow-phase13

