---
# Qallow Kubernetes Namespace and RBAC Configuration

apiVersion: v1
kind: Namespace
metadata:
  name: qallow
  labels:
    name: qallow
    monitoring: enabled

---
# Service Account for Qallow services
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qallow-sa
  namespace: qallow

---
# ClusterRole for Qallow services
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qallow-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create"]

---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: qallow-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: qallow-role
subjects:
- kind: ServiceAccount
  name: qallow-sa
  namespace: qallow

---
# NetworkPolicy for Qallow namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qallow-network-policy
  namespace: qallow
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: qallow
    - namespaceSelector:
        matchLabels:
          name: istio-system
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: qallow
  - to:
    - namespaceSelector:
        matchLabels:
          name: istio-system
  - to:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53

---
# ResourceQuota for Qallow namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: qallow-quota
  namespace: qallow
spec:
  hard:
    requests.cpu: "100"
    requests.memory: "200Gi"
    limits.cpu: "200"
    limits.memory: "400Gi"
    pods: "100"
    services: "20"
    persistentvolumeclaims: "10"

---
# LimitRange for Qallow namespace
apiVersion: v1
kind: LimitRange
metadata:
  name: qallow-limits
  namespace: qallow
spec:
  limits:
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "8"
      memory: "16Gi"
    min:
      cpu: "200m"
      memory: "256Mi"
    type: Pod

