# Discrete hyperparameter space for QAOA search
learning_rate:
  values: [0.0001, 0.0003, 0.001, 0.003]
optimizer:
  values: [adam, adamw]
layers:
  values: [2, 3, 4, 5]
batch_size:
  values: [16, 32, 64, 128]
