name: Qallow Internal CI

on:
  push:
    branches:
      - main
      - develop
      - release/**
  pull_request:

jobs:
  build-and-test:
    name: Build and Accelerator Smoke
    runs-on: ubuntu-22.04
    container:
      image: nvidia/cuda:13.0.0-devel-ubuntu22.04
      options: --ipc=host

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            build-essential \
            gcc \
            g++ \
            make \
            python3 \
            python3-pip \
            git \
            ninja-build

      - name: Install Python packages
        run: |
          pip3 install --upgrade pip
          pip3 install sentence-transformers
          python3 -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')"

      - name: Build CPU binary
        run: make ACCELERATOR=CPU -j"$(nproc)"

      - name: Run smoke tests
        run: tests/smoke/test_modules.sh

      - name: Accelerator execution
        env:
          QALLOW_QUIET: "1"
        run: |
          echo "{}" > /tmp/accelerator_input.json
          ./build/CPU/qallow_unified_cpu run --accelerator --file=/tmp/accelerator_input.json --no-watch --threads=2 --quiet

      - name: Dependency report
        continue-on-error: true
        run: scripts/check_dependencies.sh
