name: Qallow Internal CI

on:
  push:
    branches:
      - main
      - develop
      - release/**
  pull_request:

jobs:
  build-and-test:
    name: Build and Accelerator Smoke
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
      options: --ipc=host

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          # Remove unnecessary files to free up space
          rm -rf /usr/local/lib/android
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf /opt/hostedtoolcache
          df -h

      - name: Install system dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            build-essential \
            gcc \
            g++ \
            make \
            python3 \
            python3-pip \
            git \
            ca-certificates
          apt-get clean
          rm -rf /var/lib/apt/lists/*

      - name: Install Python packages
        run: |
          pip3 install --upgrade pip --no-cache-dir

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: build/
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build CPU binary
        run: |
          echo "Starting build with $(nproc) cores..."
          make ACCELERATOR=CPU -j"$(nproc)" || {
            echo "Build failed, checking disk space..."
            df -h
            exit 1
          }
          echo "Build completed successfully"
          ls -lh build/CPU/qallow_unified_cpu

      - name: Verify binary exists
        run: |
          if [ ! -f build/CPU/qallow_unified_cpu ]; then
            echo "ERROR: Binary not found at build/CPU/qallow_unified_cpu"
            ls -la build/CPU/ || echo "build/CPU directory does not exist"
            exit 1
          fi
          echo "Binary verified: $(file build/CPU/qallow_unified_cpu)"

      - name: Run smoke tests
        run: |
          echo "Running smoke tests..."
          bash tests/smoke/test_modules.sh || {
            echo "Smoke tests failed"
            exit 1
          }

      - name: Accelerator execution
        env:
          QALLOW_QUIET: "1"
        run: |
          echo "{}" > /tmp/accelerator_input.json
          ./build/CPU/qallow_unified_cpu run --accelerator --file=/tmp/accelerator_input.json --no-watch --threads=2 --quiet

      - name: Clean up build artifacts
        if: always()
        run: |
          rm -rf build/
          df -h

      - name: Dependency report
        continue-on-error: true
        run: scripts/check_dependencies.sh
